apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app: "true"
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "false"
          image: redis:6.0.8
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
